import type { AstroComponentFactory } from 'astro/runtime/server/index.js'

import PriorityInequity from '@/components/priority/PriorityInequity.astro'
import Analytics from '@/components/analytics/Analytics.astro'
import Welcome from '@/components/Welcome.astro'
import PrioritySDoH from '@/components/priority/PrioritySDoH.astro'
import PrioritySelector from '@/components/PrioritySelector.astro'
import StratifiedIndicator from '@/components/StratifiedIndicator.astro'

import type {
  MaternalMortalityRateRow,
  ForestPlotDataRow,
  AnalyticsRow,
  ScatterRow,
  StratifiedRow,
} from '@/lib/parquet'
import type { IndicatorStratifier } from '@/config/general'
import { priorities } from '@/config/general'

export interface PageProps {
  title: string
  text: string
  dimension?: string
  subdimensions?: string[]
  pages: unknown[]
  slug: string | undefined
  date: Date
  source?: string
  data?: MaternalMortalityRateRow[]
  forestPlotData?: ForestPlotDataRow[]
  analyticsData?: AnalyticsRow[]
  scatterData?: ScatterRow[]
  trasladoData?: StratifiedRow[]
  frecuenciaTransporteData?: StratifiedRow[]
  sobrecargaCuidadosData?: StratifiedRow[]
  empleoInformalData?: StratifiedRow[]
  coberturaProgramaData?: StratifiedRow[]
  controlesPrenatalData?: StratifiedRow[]
  apoyoInfantilData?: StratifiedRow[]
  stratifiers?: IndicatorStratifier[]
}

type PropsResolver = (
  props: PageProps,
  baseUrl: string,
) => Record<string, unknown>

interface PageRegistryEntry {
  component: AstroComponentFactory
  resolveProps: PropsResolver
}

const base = (url: string, path: string) => `${url}/data/${path}`

const STRATIFIED_MOCK_YEARS = [
  2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025,
]

export const pageRegistry: Record<string, PageRegistryEntry> = {
  // ─── No slug (home) ────────────────────────────────────────────────────────
  '': {
    component: Welcome,
    resolveProps: ({ text }) => ({ text }),
  },

  // ─── Section index pages ───────────────────────────────────────────────────
  'analisis-de-inequidad': {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },
  'determinantes-de-la-salud': {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },
  analisis: {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },

  // ─── Detail pages ──────────────────────────────────────────────────────────
  'determinantes-de-la-salud/mortalidad-materna': {
    component: PrioritySDoH,
    resolveProps: ({ title, text }) => ({ title, text }),
  },
  'analisis-de-inequidad/mortalidad-materna': {
    component: PriorityInequity,
    resolveProps: ({ title, text, data, source }, baseUrl) => ({
      title,
      text,
      data,
      source,
      csvPath: base(baseUrl, 'maternal_mortality_rate.csv'),
    }),
  },
  'analisis/mortalidad-materna': {
    component: Analytics,
    resolveProps: (
      { title, text, forestPlotData, analyticsData, scatterData },
      baseUrl,
    ) => {
      // Years generated by the R mock scripts (2016–2025).
      // GeoJSONs are generated per-year; the frontend only uses years that
      // appear in the actual data, so extra entries here are harmless.
      const MOCK_YEARS = [
        2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025,
      ]
      const DSS_INDICATORS = [
        'traslado',
        'embarazadas-empleo-informal',
        'sobrecarga-embarazadas',
        'apoyo-embarazadas',
        'frecuencia-transporte',
        'apoyo-infantil',
      ] as const

      const geojsonUrls = Object.fromEntries(
        DSS_INDICATORS.map((ind) => [
          ind,
          Object.fromEntries(
            MOCK_YEARS.map((yr) => [
              yr,
              base(baseUrl, `bivariate-${ind}-${yr}.geojson`),
            ]),
          ),
        ]),
      ) as Record<string, Record<number, string>>

      const priorityGeojsonUrls = Object.fromEntries(
        MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `mortalidad-materna-${yr}.geojson`),
        ]),
      ) as Record<number, string>

      const dssBivariateGeojsonUrls = Object.fromEntries(
        DSS_INDICATORS.map((ind_x) => [
          ind_x,
          Object.fromEntries(
            DSS_INDICATORS.filter((ind_y) => ind_y !== ind_x).map((ind_y) => [
              ind_y,
              Object.fromEntries(
                MOCK_YEARS.map((yr) => [
                  yr,
                  base(
                    baseUrl,
                    `bivariate-dss-${ind_x}-${ind_y}-${yr}.geojson`,
                  ),
                ]),
              ),
            ]),
          ),
        ]),
      )

      return {
        priority: priorities[0],
        title,
        text,
        forestPlotData,
        analyticsData,
        scatterData,
        geojsonUrls,
        priorityGeojsonUrls,
        dssBivariateGeojsonUrls,
        csvUrl: base(baseUrl, 'scatter.csv'),
      }
    },
  },
  traslado: {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        trasladoData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: trasladoData ?? [],
      yAxisLabel: '% mujeres embarazadas',
      csvPath: base(baseUrl, 'traslado.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `traslado-${yr}.geojson`),
        ]),
      ),
    }),
  },
  'frecuencia-transporte': {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        frecuenciaTransporteData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: frecuenciaTransporteData ?? [],
      yAxisLabel: '% población con acceso',
      csvPath: base(baseUrl, 'frecuencia-transporte.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `frecuencia-transporte-${yr}.geojson`),
        ]),
      ),
    }),
  },
  'sobrecarga-embarazadas': {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        sobrecargaCuidadosData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: sobrecargaCuidadosData ?? [],
      yAxisLabel: '% mujeres embarazadas',
      csvPath: base(baseUrl, 'sobrecarga-embarazadas-municipal.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `sobrecarga-embarazadas-${yr}.geojson`),
        ]),
      ),
    }),
  },
  'embarazadas-empleo-informal': {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        empleoInformalData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: empleoInformalData ?? [],
      yAxisLabel: '% personas con empleo informal',
      csvPath: base(baseUrl, 'embarazadas-empleo-informal.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `embarazadas-empleo-informal-${yr}.geojson`),
        ]),
      ),
    }),
  },
  'apoyo-embarazadas': {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        coberturaProgramaData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: coberturaProgramaData ?? [],
      yAxisLabel: '% mujeres embarazadas',
      csvPath: base(baseUrl, 'apoyo-embarazadas.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `apoyo-embarazadas-${yr}.geojson`),
        ]),
      ),
    }),
  },
  'apoyo-infantil': {
    component: StratifiedIndicator,
    resolveProps: (
      {
        title,
        text,
        dimension,
        subdimensions,
        stratifiers,
        apoyoInfantilData,
        source,
      },
      baseUrl,
    ) => ({
      title,
      text,
      dimension,
      source,
      subdimensions: subdimensions ?? [],
      stratifiers: stratifiers ?? [],
      data: apoyoInfantilData ?? [],
      yAxisLabel: '% mujeres embarazadas',
      csvPath: base(baseUrl, 'apoyo-infantil.csv'),
      geojsonUrls: Object.fromEntries(
        STRATIFIED_MOCK_YEARS.map((yr) => [
          yr,
          base(baseUrl, `apoyo-infantil-${yr}.geojson`),
        ]),
      ),
    }),
  },
}
