import type { AstroComponentFactory } from 'astro/runtime/server/index.js'

import MaternalMortalityInequity from '@/components/maternal-mortality/MaternalMortalityInequity.astro'
import Analytics from '@/components/analytics/Analytics.astro'
import Welcome from '@/components/Welcome.astro'
import MaternalMortalitySDoH from '@/components/maternal-mortality/MaternalMortalitySDoH.astro'
import PrioritySelector from '@/components/PrioritySelector.astro'
import StratifiedIndicator from '@/components/StratifiedIndicator.astro'

import type {
  AnalyticsDataRow,
  MaternalMortalityRateRow,
  ForestPlotDataRow,
  AnalyticsMaternalRow,
  ScatterMaternalRow,
  StratifiedRow,
} from '@/lib/parquet'

export interface PageProps {
  title: string
  text: string
  pages: unknown[]
  slug: string | undefined
  date: Date
  data?: AnalyticsDataRow[] | MaternalMortalityRateRow[]
  forestPlotData?: ForestPlotDataRow[]
  analyticsMaternalData?: AnalyticsMaternalRow[]
  scatterMaternalData?: ScatterMaternalRow[]
  trasladoData?: StratifiedRow[]
  frecuenciaTransporteData?: StratifiedRow[]
  sobrecargaCuidadosData?: StratifiedRow[]
  empleoInformalData?: StratifiedRow[]
  coberturaProgramaData?: StratifiedRow[]
  controlesPrenatalData?: StratifiedRow[]
}

type PropsResolver = (
  props: PageProps,
  baseUrl: string,
) => Record<string, unknown>

interface PageRegistryEntry {
  component: AstroComponentFactory
  resolveProps: PropsResolver
}

const base = (url: string, path: string) => `${url}/data/${path}`

export const pageRegistry: Record<string, PageRegistryEntry> = {
  // ─── No slug (home) ────────────────────────────────────────────────────────
  '': {
    component: Welcome,
    resolveProps: ({ text }) => ({ text }),
  },

  // ─── Section index pages ───────────────────────────────────────────────────
  'analisis-de-inequidad': {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },
  'determinantes-de-la-salud': {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },
  analisis: {
    component: PrioritySelector,
    resolveProps: ({ title, text, slug }) => ({ title, text, section: slug }),
  },

  // ─── Detail pages ──────────────────────────────────────────────────────────
  'determinantes-de-la-salud/mortalidad-materna': {
    component: MaternalMortalitySDoH,
    resolveProps: ({ title, text }) => ({ title, text }),
  },
  'analisis-de-inequidad/mortalidad-materna': {
    component: MaternalMortalityInequity,
    resolveProps: ({ title, text, data }, baseUrl) => ({
      title,
      text,
      data,
      csvPath: base(baseUrl, 'maternal_mortality_rate.csv'),
    }),
  },
  'analisis/mortalidad-materna': {
    component: Analytics,
    resolveProps: (
      {
        title,
        text,
        forestPlotData,
        analyticsMaternalData,
        scatterMaternalData,
      },
      baseUrl,
    ) => {
      // Years generated by the R mock scripts (2016–2025).
      // GeoJSONs are generated per-year; the frontend only uses years that
      // appear in the actual data, so extra entries here are harmless.
      const MOCK_YEARS = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
      const DSS_INDICATORS = [
        'traslado',
        'empleo_informal',
        'sobrecarga',
        'cobertura_programa',
        'transporte',
      ] as const

      const geojsonUrls = Object.fromEntries(
        DSS_INDICATORS.map((ind) => [
          ind,
          Object.fromEntries(
            MOCK_YEARS.map((yr) => [yr, base(baseUrl, `mock_bivariate_${ind}_${yr}.geojson`)]),
          ),
        ]),
      ) as Record<string, Record<number, string>>

      const maternalGeojsonUrls = Object.fromEntries(
        MOCK_YEARS.map((yr) => [yr, base(baseUrl, `mock_maternal_mortality_${yr}.geojson`)]),
      ) as Record<number, string>

      const dssBivariateGeojsonUrls = Object.fromEntries(
        DSS_INDICATORS.map((ind_x) => [
          ind_x,
          Object.fromEntries(
            DSS_INDICATORS.filter((ind_y) => ind_y !== ind_x).map((ind_y) => [
              ind_y,
              Object.fromEntries(
                MOCK_YEARS.map((yr) => [
                  yr,
                  base(baseUrl, `mock_bivariate_dss_${ind_x}_${ind_y}_${yr}.geojson`),
                ]),
              ),
            ]),
          ),
        ]),
      )

      return {
        title,
        text,
        forestPlotData,
        analyticsMaternalData,
        scatterMaternalData,
        geojsonUrls,
        maternalGeojsonUrls,
        dssBivariateGeojsonUrls,
        csvUrl: base(baseUrl, 'mock_scatter_maternal.csv'),
      }
    },
  },
  traslado: {
    component: StratifiedIndicator,
    resolveProps: ({ title, text, trasladoData }, baseUrl) => ({
      title,
      text,
      data: trasladoData ?? [],
      yAxisLabel: 'Minutos promedio',
      csvPath: base(baseUrl, 'journey_time.csv'),
    }),
  },
  'frecuencia-transporte': {
    component: StratifiedIndicator,
    resolveProps: ({ title, text, frecuenciaTransporteData }, baseUrl) => ({
      title,
      text,
      data: frecuenciaTransporteData ?? [],
      yAxisLabel: 'Buses por hora',
      csvPath: base(baseUrl, 'transport_frequency.csv'),
    }),
  },
  'sobrecarga-embarazadas': {
    component: StratifiedIndicator,
    resolveProps: ({ title, text, sobrecargaCuidadosData }, baseUrl) => ({
      title,
      text,
      data: sobrecargaCuidadosData ?? [],
      yAxisLabel: '% mujeres embarazadas',
      csvPath: base(baseUrl, 'care_overload.csv'),
    }),
  },
  'embarazadas-empleo-informal': {
    component: StratifiedIndicator,
    resolveProps: ({ title, text, empleoInformalData }, baseUrl) => ({
      title,
      text,
      data: empleoInformalData ?? [],
      yAxisLabel: '% mujeres embarazadas',
      csvPath: base(baseUrl, 'informal_employment.csv'),
    }),
  },
  'apoyo-embarazadas': {
    component: StratifiedIndicator,
    resolveProps: ({ title, text, coberturaProgramaData }, baseUrl) => ({
      title,
      text,
      data: coberturaProgramaData ?? [],
      yAxisLabel: '% de embarazadas',
      csvPath: base(baseUrl, 'program_cover.csv'),
    }),
  },
}
